In [ ]:
def writetoafile(filename,data):
    withopen

In [15]:
def readfromfile(filename):
    with open(filename,"r") as f:
        fd = f.read()
        f.close()
    return fd
filename ="data.txt"
readfromfile("data.txt")
def printlines(filename):
    with open(filename,"r") as f:
        for line in f:
            print(line,end=" ")
        return
printlines(filename)
print(readfromfile(filename))


FileNotFoundError: [Errno 2] No such file or directory: 'data.txt'

# numpy

* Numpy is an advanced library
* numpy is a numerical python  
* numpy is to perform mathematical and sta
tistical operations
* the values are represented in the form of rows and columns
** advantages of numpy when compared to list **
          * it|


In [7]:
import numpy as np

In [8]:
# creating an array using numpy
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# checking the number of elements
a.size

9

In [13]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a+4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [18]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
a2.size

8

In [24]:
a2=np.array([[1,2,3,4],[5,6,7,8]],dtype=complex)
a2

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [26]:
### comparision of two arrays

a=np.array([[3,4,5,6],[9,8,7,2]])
b=np.array([[1,2,3,4],[9,8,7,4]])

In [27]:
a+b

array([[ 4,  6,  8, 10],
       [18, 16, 14,  6]])

In [28]:
a-b

array([[ 2,  2,  2,  2],
       [ 0,  0,  0, -2]])

In [29]:
a>b

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [30]:
a<b

array([[False, False, False, False],
       [False, False, False,  True]])

In [31]:
a**b

array([[        3,        16,       125,      1296],
       [387420489,  16777216,    823543,        16]], dtype=int32)

In [32]:
a<b

array([[False, False, False, False],
       [False, False, False,  True]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
a

array([[3, 4, 5, 6],
       [9, 8, 7, 2]])

In [41]:
a[1:2,3:4]

array([[2]])

In [42]:
a[:,2:3]

array([[5],
       [7]])

In [43]:
a[:,:]

array([[3, 4, 5, 6],
       [9, 8, 7, 2]])

In [45]:
a[:,0:2]

array([[3, 4],
       [9, 8]])

In [46]:
a.shape

(2, 4)

In [47]:
a.itemsize

4

In [48]:
a.reshape

<function ndarray.reshape>

In [50]:
b=np.arange(3,9)
b

array([3, 4, 5, 6, 7, 8])

In [51]:
b=np.arange(3,9)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [52]:
b.reshape(3,2)

array([[3, 4],
       [5, 6],
       [7, 8]])

In [53]:
b.reshape(2,3)

array([[3, 4, 5],
       [6, 7, 8]])

In [55]:
min(b)

3

In [56]:
np.std(b)

1.707825127659933

In [57]:
np.mean(b)

5.5

In [58]:
np.sum(b)

33

In [59]:
np.var(b)

2.9166666666666665

In [60]:
np.cumsum(b)

array([ 3,  7, 12, 18, 25, 33], dtype=int32)

In [61]:
b

array([3, 4, 5, 6, 7, 8])

In [62]:
np.argmin(b)

0

In [63]:
np.argmax(b)

5

In [64]:
np.transpose(b)

array([3, 4, 5, 6, 7, 8])

In [65]:
a.transpose()

array([[3, 9],
       [4, 8],
       [5, 7],
       [6, 2]])

In [100]:
b=int(input())
d=0
i=0
while b!=0:
    binary=b%10
    d=d+binary*(2**i)
    b=b//10
    i=i+1
print(d)

1011
11


### decimal to binary

In [98]:
s="12345"
def reversestring(s):
    return s[-1::-1]
reversestring(s)

'54321'